apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: k97yn9fqb-python 
  janus-idp.io/tekton: k97yn9fqb-python
  backstage.io/kubernetes-id: k97yn9fqb-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: k97yn9fqb-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml